### ISSUE TITLE
LosslessSwitcher

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-extras#10]
### Cask name

losslessswitcher

### GUI or CLI

GUI

### Software official website

https://github.com/vincentneo/LosslessSwitcher

### Last version

 1.1.0-hqplayer2

### Description

Automatically switch the sampling rate based on the played audio.

### Download URL

https://github.com/vincentneo/LosslessSwitcher/releases/download/1.1.0-hqplayer2/LosslessSwitcher-build18.app.zip

### Charging model

Free

**Comment by Mrered** [comment]
```
~/Library/Preferences/com.vincent-neo.LosslessSwitcher.plist
```

**Comment by ivaquero** [comment]
Done
