### ISSUE TITLE
Blip

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-extras#128]
### Cask name

Blip

### GUI or CLI

GUI

### Software official website

https://blip.net/

### Description

Cross-platform client for peer-to-peer file exchange with support for resuming downloads from where they were left off.

### Charging model

Free

**Comment by cnderrick** [comment]
> ### Cask name
> Blip
> 
> ### GUI or CLI
> GUI
> 
> ### Software official website
> https://blip.net/
> 
> ### Last version
> _No response_
> 
> ### Description
> Cross-platform client for peer-to-peer file exchange with support for resuming downloads from where they were left off.
> 
> ### Download URL
> _No response_
> 
> ### Charging model
> Free

brew官方支持这个app，你可以直接安装
```
 user@Computer  ~  brew search blip --cask
==> Casks
blip                                     blisk
```

**Comment by Mrered** [comment]
已在官方库中

```sh
❯ brew abv blip
==> blip: 1.0.13,20240820101306
https://blip.net/
Not installed
From: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git
==> Name
blip
==> Description
Send any size file between devices
==> Artifacts
Blip.app (App)
```
