### ISSUE TITLE
The original author adopted a new file name structure when publishing

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-extras#160]
https://github.com/Brewforge/homebrew-extras/blob/e2ea76621b3d83b5ca695812830957b7cb384d8b/Casks/lyricsxjh.rb#L5

`https://github.com/MxIris-LyricsX-Project/LyricsX/releases/download/v1.6.7/LyricsX.2024-07-24.21-39-21.zip`

**Comment by Mrered** [comment]
并且作者好像更改了仓库名称

**Comment by Mrered** [comment]
Actions 运行结果：

https://github.com/Brewforge/homebrew-extras/actions/runs/10069059653/job/27835439342#step:5:114

**Comment by ivaquero** [comment]
Done
