### ISSUE TITLE
magicquit

### ISSUE THREAD

**Issue by Mrered** [Brewforge/homebrew-extras#173]
### Cask name

magicquit

### GUI or CLI

GUI

### Software official website

https://magicquit.com/

### Last version

1.4

### Description

Automatically closes apps when you don't use them anymore.

### Download URL

https://magicquit.com/apps/MagicQuit_1.4.dmg

### Charging model

Free

**Comment by cnderrick** [comment]
官方已经有了。

 ~  brew info magicquit
==> magicquit: 1.4
https://magicquit.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/m/magicquit.rb
==> Name
MagicQuit
==> Description
Efficiency tool for automatically closing apps when they are not in use
==> Artifacts
MagicQuit.app (App)
==> Analytics
install: 53 (30 days), 53 (90 days), 53 (365 days)

**Comment by ivaquero** [comment]
那先关了哈
