### ISSUE TITLE
能否去掉bun

### ISSUE THREAD

**Issue by bingtsingw** [Brewforge/homebrew-extras#84]
### Verification

- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.

### Description of issue

bun有官方的的tap: `oven-sh/bun/bun`
两个都安装的话，会有冲突

### Command that failed

brew install bun

### Output of command with `--verbose --debug`

```shell
Error: Formulae found in multiple taps:
       * oven-sh/bun/bun
       * brewforge/extras/bun
```
```


### Output of `brew doctor` and `brew config`

```shell
~
```

### Output of `brew tap`

```shell
~
```

**Comment by ivaquero** [comment]
可以，稍等

**Comment by ivaquero** [comment]
搞定
